### ISSUE TITLE
UnitConvert3 is not showing a file browser in configure

### ISSUE THREAD

**Issue by evertvorster** [vegastrike/Tools#3]
Hey, this is the first time I managed to get this tool to work on the Python3 version. 

It's only a small niggle, but when I click on "Browse" to locate my installation of VegaStrike, I get an error message in the console, and no file browser.

Here is the error message:

[evert@Vorster UnitConverter3]$ ./uc
iniRead: config variable Config/WORKDIR not yet set
iniRead: config variable Config/VEGASTRIKE_ROOT not yet set
iniRead: FAILED reading active model
Reading workspace
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "unitconverter.py", line 2694, in <lambda>
    Button(iframe, text='Browse', command=lambda:self.getFolder(self.vegastrike)).pack(side=LEFT, padx=5)
  File "unitconverter.py", line 467, in getFolder
    folder = askdirectory(initialdir=self.vegastrike.get(), title="Select A Folder", mustexist=1)
NameError: name 'askdirectory' is not defined

**Comment by P-D-E** [comment]
Replace
`folder = askdirectory(initialdir=self.vegastrike.get(), title="Select A Folder", mustexist=1)`

with
`folder = filedialog.askdirectory(initialdir=self.vegastrike.get(), title="Select A Folder", mustexist=1)`

That one escaped the first-pass conversion

**Comment by P-D-E** [comment]
...on a side note, here's a prototype with split csv handling support:

https://github.com/P-D-E/Tools/tree/split_csv/modtools/UnitConverter3

The new combo box at the top of the Unit section gets preloaded with all the .csv files found in the units subdir of the path specified in Config; select one and press Load, the rest of the GUI will work on that file.

**Comment by P-D-E** [comment]
...and after some updates, here's a PR:
https://github.com/vegastrike/Tools/pull/4
